### ISSUE TITLE
support-zeek-40 branch compile errors (no BroString.h ) on latest zeek

### ISSUE THREAD

**Issue by maofeichen** [MITRECND/bro-http2#15]
Hello,

I noticed that the plugin has a "support-zeek-40" branch which seem compatible with zeek 4.x. However, I tested it with latest zeek master(via git clone --recursive https://github.com/zeek/zeek), and this plugin couldn't compile successfully. 

I used the specific branch:
```sh
$ git branch
* support-zeek-40
```

 Both required packages: Nghttp2 and Brotli were installed, and the configure output:
```sh
$ ./configure --zeek-dist=/home/zeek/Documents/zeek-master
Build Directory        : build
Zeek Source Directory   : /home/zeek/Documents/zeek-master
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test cxx17_already_works
-- Performing Test cxx17_already_works - Failed
-- Performing Test cxx17_works
-- Performing Test cxx17_works - Success
-- Zeek executable      :
-- Zeek source          : /home/zeek/Documents/zeek-master
-- Zeek build           : /home/zeek/Documents/zeek-master/build
-- Zeek install prefix  : /usr/local/zeek
-- Zeek plugin directory: /usr/local/zeek/lib/zeek/plugins
-- Zeek debug mode      : false
-- Found LibNGHTTP2: /usr/lib/x86_64-linux-gnu/libnghttp2.so (found version "1.40.0")
-- Found LibBROTLI: /usr/local/lib/libbrotlidec.so
-- ---------------------
-- LibBROTLI ROOT DIR  : /usr/local
-- LibBROTLI INC DIR   : /usr/local/include/brotli
-- LibBROTLI LIB DIR   : /usr/local/lib/libbrotlidec.so
-- ---------------------
-- LibNGHTTP2 ROOT DIR : /usr
-- LibNGHTTP2 INC DIR  : /usr/include/nghttp2
-- LibNGHTTP2 LIB DIR  : /usr/lib/x86_64-linux-gnu/libnghttp2.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zeek/Documents/bro-http2/build
```

However, when I tried to compile, errors were shown as:
```sh
$ make
[  5%] Built target bif-plugin-mitrecnd_HTTP2-events.bif
[  5%] Built target generate_outputs
[ 10%] Built target bif-plugin-mitrecnd_HTTP2-http2.bif
[ 15%] Creating __bro_plugin__ for mitrecnd::HTTP2
[ 15%] Built target bro-plugin-mitrecnd_HTTP2
[ 15%] Built target copy-scripts-mitrecnd_HTTP2
[ 15%] Built target bif-init-mitrecnd_HTTP2
[ 21%] Building CXX object CMakeFiles/mitrecnd-HTTP2.linux-x86_64.dir/src/Plugin.cc.o
In file included from /home/zeek/Documents/bro-http2/src/HTTP2_Stream.h:10,
                 from /home/zeek/Documents/bro-http2/src/HTTP2.h:19,
                 from /home/zeek/Documents/bro-http2/src/Plugin.cc:2:
/home/zeek/Documents/bro-http2/src/HTTP2_HeaderStorage.h:6:10: fatal error: BroString.h: No such file or directory
    6 | #include "BroString.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/mitrecnd-HTTP2.linux-x86_64.dir/build.make:101: CMakeFiles/mitrecnd-HTTP2.linux-x86_64.dir/src/Plugin.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:143: CMakeFiles/mitrecnd-HTTP2.linux-x86_64.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

It seems [issue 9](https://github.com/MITRECND/bro-http2/issues/9) is a similar issue, which had been fixed, but on zeek 3.x.  So I assume that the plugin hasn't support zeek 4.x yet? And if it's possible, how to fix this error?

Thanks for your help!

**Comment by eooi** [comment]
Seeing the same on the official Zeek 4.1 release version.

**Comment by maofeichen** [comment]
After some trial and errors, I "kind of" figured out how to configure the plugin to work on zeek lts 4.0.3. 
Here is what I've tried:
1. use the [latest released version](https://github.com/MITRECND/bro-http2/releases/tag/0.5.3) instead of any master/other branches. The released version can compile (with warnings but can finish compiling) with zeek lts version (4.0.0/4.0.3).
2. after compile, `make test` pass all 3 tests on 4.0.0, but failed 2 on 4.0.3. But I installed the plugin any way.
3. after install, if tried to run the plugin with zeek via `@load http2` according to instructions directly, zeek give errors:
    > ... main.zeek, line 160: argument type mismatch in event invocation (conn_weird ...

    It's due to zeek updated the event parameters after 4.x. To fix it, modify the line 160 of main.zeek file of the http2 plugin as:
    ```zeek
    if ( method !in HTTP::http_methods )
        event conn_weird("unknown_HTTP2_method", c, method, "HTTP2_Analyzer");
    ```
    Actually this is what the developer had already patched on `support-zeek-40` branch.
4. after the patch, the plugin can be loaded without issues. And I tested it with zeek 4.0.3, with a nginx turning on http2 as the sever, and `curl` as the client on localhost. A simple request were issued on localhost:80 (h2c), a `http2.log` were generated as:
    > $ cat http2.log | jq -c
{"ts":1630651146.601634,"uid":"CMShqr1avfFuOKvyK","id.orig_h":"::1","id.orig_p":59400,"id.resp_h":"::1","id.resp_p":80,"stream_id":1,"method":"GET","host":"localhost","uri":"/","version":"2.0","user_agent":"curl/7.61.1","request_body_len":0,"response_body_len":4057,"status_code":200,"status_msg":"<empty>","push":false}

Even without a thorough test, it seems that the plugin can function on current zeek lts version, so I closed this issue, thanks!
